language: node_js
node_js: 10.21.0
install: npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: El7HbY5PqsHd5QDUzOIQ+5R6tP1IbfFqms2y4tfvUrrzb2emozdPO0UQFIarJ7ObPl2kgmwG0OWktzc8WSlvirq98h9PnHcuu2AkjAvk1TPvPcJ2CR+yfXlUTLFIPw5FIsAq3Ulh87Vv/EVNTJu2G1MZUP7qJlMOS50qS4Ric+kD9sT3vJMfovE/SXLhwwu4asb3aAfP9jqNj8fYi2Jlv2MNEyqETj04CYitJifSESOZj190VX5R4cuVYJWKb9yoBFRz9KzjRZMHZ0vUKFhhN7nZBzXcIcW+qenM2ejS6SKZP133PZEUAr8fm+Ec1ca/ca/jui3BI+ObqH/CXZ20DrvZg7I8oiyGjXEVARHNCzzuG6utydoXsO4/1RLPbwyRj6Vvg/HfbMX4GQIa4JQwzF81jbadSJ/IWhylpkRtI8n1eCq3yBsGZBHZIsYvOhsZzx1tvBNUyXTojXL7ZSEsrX3Ao/Uc5QeOyDsgiE9/BX81h7sntipO5Hiqbua8oypUnpx/h4hfIBIqWsouahIer02cOCYa9vQD9zY9Duuamz7XVD6LZvMqhqJ2cyfwLXp6kAbvFs3D5Gvll/BBzPTGyye6JPwAICQGCns8rFeyynxQR2y6at7nTh2FuQcq34tBpXDocifYkX5esfijHvVJcflhg1l5v1wr1r/3rfaedZ4=