language: node_js
node_js: 10.21.0

install: npm install
script:
  - npm test 
deploy:
  provider: heroku
  api_key:
    secure: RIebdH3A5/psNVPRn5VdW2ZJb6cOfTmy97ZdP+JLRlOJy6kcUvz91f/dc0GiTloCEqkxHV1t6Os3imbUw5jGhse83rz/oRXZxnxWfHfEUikcURvR6532FKuAUxGCv07+X7YTptnDpcT8+Xo/F54Kd/QWIhkin7T8uwhmxRH7BHnkt/3b/02MzdbLB55MUK0cquoE+lW8TNbanMAxCvII2LZ6Pp5ZMnt+BXoXYI4G5qI5+/dfJ9AjCKYYtWvAbdV5neNZsupVv2nm7MVHlyk1TcNb4K1gJQ6NosQ/WF/L3X1UOFvbOPgzNS0d5SGCfPjiWQI9ttsd0WmZh020SCpiO2n5D0AQoK+q1OXlZfecd/7jRvLbkPqh7wul/19JT8nCLZs9TCdQeXd0FCh5nXNyg4wORq8eBIdGRY36v22r+IkvihJ2Rq6KcU8NYyxyjSt3U5h7RoF1/sL9/7e95hxpCbzByN1g54GZ4f+VQly8UqgrRuBhkNOLi5tE4ekz7to7XcTFqGf7U9MDZ0UK/KofmliRrA4tGP6tlOdSL4EsjUB33/Y186PBYi7u2VfLtgqfHNoXDvoijiwGx8DzHLQkDJoFwHKAL2NLN2uRLK8hs2yTFdwGwX7PnCaznlJCfLg4GD79jDQkDfX5lpGv9WSAvASNBeASdWxqmmqriQ7frJA=