language: node_js
node_js: 10.21.0

install: npm install
script:
  - npm test 
deploy:
  provider: heroku
  api_key:
    secure: Y6LTfXw6feY4GslmhHiYT+99P/ioE61vChdjbSjZ2de1f06SSbMdABXVEzwYZK+PCpRBh2wxlLpWM2rxxmn8fm+FTenMuSF+3torMsBG/6qSOnej5Q9VcHazFUVzL5spKFLI/vG63Hs7BCL/aFn7Hg4xojvOVRorZ9q+aHkIR9oPyf91Hw+Vg6byjj1v3n42fvZez1xG2e/eEdme2A6Ob8XToH36sy2zPdm8RbP61esnb8UMG4ZRP8ej+rhrIHoJUtGOIA6yNPUQApkmfDjno4klb+CX0Kr+BkaLPrJli2i60sEE8SL9qtH8oku+5nm/HU7V/lshvyNIw9m0eLWy4u6IDApGzDgoR9VfJu2vDiCU4zw/iQJtvocs4rwsC4B82U7k7fQJ7GhxaZ9EUbDfJIAMJ3SribFWor9BLxoyAi8oDlvWB2ZBFTfSQGZlOc9hZDmw3HJd6+xnIvxTGZ5Ktb+sUi1ioBs8hUxCK5/s8dflaX91lWC71rn1hvNgCFQxi9KUcIKiEM9ReErfmqzsL/DRgRLjLFwerXqR76i2aQySZqSPtmmUIzuOc2U1r3D/JkcflQED2019Fq8OHJZRKGnfz3q8ofjDOuyDQQHuMDyBsDd5LzAxWUpap67Ey9l0I/obaYEe/CaS2Y0D3TwoGWGWeQP3vVAStcq2SupG4XQ=